### ISSUE TITLE
Support updating bot avatar globally via MeBot console

### ISSUE THREAD

**Issue by jso0003auburn** [MeBots/MeBots#24]
I noticed that when I update the bot avatar on MeBots it doesn't transfer over to existing groups, not sure if this would require the user to re-auth the group but would be cool to be able to update it across groups automatically via changing the URL in MeBots.

**Comment by ErikBoesen** [comment]
Hm, so this is technically possible, but as it stands the user would have to log back in (and probably go to the add page, unless we really want to be hacky) for the avatars to update. Also, we'd have to start tracking the avatars that are assigned to each instance; right now we delegate that all to GroupMe.

This is a nice idea so I'll leave it open, but I don't think there's an easy way to do this because of how GroupMe's API works.
